sonar.projectKey=fastapi-ci
sonar.projectName=FastAPI CI
sonar.host.url=http://91.186.197.243:9000
sonar.token=sqa_0cd4c45348ef8ced6eebbf6ffb21f40c35e68161

sonar.sources=API
sonar.python.coverage.reportPaths=API/coverage.xml
sonar.exclusions=API/test.py