sonar.projectKey=frontend-ci
sonar.projectName=Frontend CI
sonar.host.url=http://91.186.197.243:9000
sonar.token=sqa_0cd4c45348ef8ced6eebbf6ffb21f40c35e68161

sonar.sources=Front/src
sonar.exclusions=Front/src/**/*.test.ts
sonar.javascript.lcov.reportPaths=Front/coverage/lcov.info
sonar.qualitygate.wait=true