sonar.projectKey=fastapi-ci
sonar.projectName=FastAPI CI
sonar.host.url=http://91.186.197.243:9000

sonar.sources=API
sonar.python.coverage.reportPaths=API/coverage.xml
sonar.exclusions=API/alembic/*,API/alembic.ini,API/k8s/*,API/Dockerfile,API/database.py,API/models.py,API/schemas.py,API/telegram.py,API/test_database.py,API/test.py
sonar.qualitygate.wait=true