name: FastAPI CI

on:
  push:
    branches: [ "devOps-API-lab-1" ]
  pull_request:
    branches: [ "devOps-API-lab-1" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd API
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
          pip install pipdeptree

      - name: Checking compatibility and correct installation
        run: |
          cd API
          pip check
          
      - name: Check dependencies with pipdeptree
        run: |
          cd API
          pipdeptree --warn fail

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd API
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests
        run: |
          cd API
          pytest --cov=main --cov=crud --cov-report=term test.py

  security-check:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and setup SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner
          echo "::add-path::$(pwd)/sonar-scanner/bin"

      - name: Run SonarScanner
        run: |
          sonar-scanner

  create-image:
    runs-on: ubuntu-latest
    needs: security-check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: docker login -u makslem -p Makc505450

      - name: Build and push Docker image
        run: |
          cd API
          docker build -t makslem/api-k8s:latest .
          docker push makslem/api-k8s:latest