name: Frontend CI

on:
  push:
    branches: [ "devOps-lab-1" ]
  pull_request:
    branches: [ "devOps-lab-1" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Front
          npm install

      - name: Build project
        run: |
          cd Front
          npm run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Front
          npm install

      - name: Run tests
        run: |
          cd Front
          npx vitest run --coverage

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: docker login -u makslem -p Makc505450

      - name: Build and push Docker image
        run: |
          cd Front
          docker build -t makslem/frontend-k8s:latest .
          docker push makslem/frontend-k8s:latest
